<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <h1>WriteController::addAction()</h1>
        <?php
        
        $form = $this->form;
        $form->setAttribute('action', $this->url());
        $form->prepare();
        
        echo $this->form()->openTag($form);

        echo $this->formCollection($form);

        echo $this->form()->closeTag();

        ?>
    </body>
</html>
