<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <h1>Post Details</h1>

         <dl>
             <dt>Post Title</dt>
             <dd><?php echo $this->escapeHtml($this->post->getTitle());?></dd>
             <dt>Post Text</dt>
             <dd><?php echo $this->escapeHtml($this->post->getText());?></dd>
         </dl>
    </body>
</html>
